# Generated by Django 4.2.27 on 2026-02-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='nombre_disponibles',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='livre',
            name='nombre_totaux',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
